### ISSUE TITLE
Linter crashes when adding `eslint-plugin-baseui`

### ISSUE THREAD

**Issue by jonsadka** [uber/baseweb#2754]
Running `eslint` normally successfully completes with no errors. After adding `eslint-plugin-baseui`, I get the following error:
```js
TypeError: Cannot read property 'value' of undefined
Occurred while linting /Users/jonsadka/web/src/shared/pages/explore/query-box-container-styles.js:17
    at lintStyleFunction (/Users/jonsadka/web/node_modules/eslint-plugin-baseui/src/deprecated-theme-api.js:363:22)
    at Identifier (/Users/jonsadk/web/node_modules/eslint-plugin-baseui/src/deprecated-theme-api.js:614:15)
    at listeners.(anonymous function).forEach.listener (/Users/jonsadka/web/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/jonsadka/web/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
...
```

## Code referenced in error
```js
// @flow
import {styled} from '../../theme/index';

export const ExploreAdvancedSidebar = styled<{
  $isShowingTopNav: boolean,
  $isVisible: boolean,
}>('div', ({$isShowingTopNav, $isVisible}) => ({
  background: 'white',
  ...
}));
```

## Current .eslintrc
```
/* eslint-env node */
module.exports = {
  extends: [require.resolve('eslint-config-fusion')],
  rules: {
    'baseui/deprecated-theme-api': 'warn',
    'baseui/deprecated-component-api': 'warn',
    'baseui/no-deep-imports': 'warn',
  },
  plugins: ['baseui'],
};
```
 
## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.29.0  |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by jonsadka** [comment]
NOTE: Upgrading to baseui@9.47.2 does not appear to fix the issue
