### ISSUE TITLE
Popover overrides ref provided to anchor element

### ISSUE THREAD

**Issue by hhvys** [uber/baseweb#4032]
## Current Behavior

```tsx
<Popover>
    <Button ref={buttonRef}>button</Button>
</Popover>
```
In the code above, `buttonRef` will not initialize and the consumer will not be able to access `Button` component.

## Expected Behavior
`Popover` should not completely override the ref provided to the anchor element.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.107.0  |
| React   |    v16.13.1     |
| browser |         |

- [ ] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by simPod** [comment]
Probably have the same issue but I'm not sure. React v17 and Base UI v9.108

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Popover`.
    at FontAwesomeIcon (App.js:19142:27)
    at Popover (App.js:52256:5)
    at Tooltip (App.js:56832:5)
    at StatefulContainer (App.js:52804:5)
    at StatefulContainer (App.js:56629:5)
    at StatefulTooltip (App.js:56684:24)
    at div
```
