### ISSUE TITLE
Hydration mismatch in tabs-motion and menu

### ISSUE THREAD

**Issue by utftufutukgyftryidytftuv** [uber/baseweb#4926]
## Current Behavior
React gets a mismatched html between ssr and hydration phases. The problem is actual for tabs-motion and menu components

```
Warning: Prop `id` did not match. Server: "bui1val-0" Client: "bui2val-0"
    at li
    at DevConsumer
    at Styled(li)
    at MaybeChildMenu (webpack-internal:///./node_modules/baseui/esm/menu/maybe-child-menu.js:35:14)
    at OptionList (webpack-internal:///./node_modules/baseui/esm/menu/option-list.js:47:28)
```

[Example](https://stackblitz.com/edit/github-fucz3s?file=pages%2Findex.js)

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v11  |
| React   |    17 and 18     |

- [x] I have searched the [issues](https://github.com/uber/baseweb/issues) of this repository and believe that this is not a duplicate.

**Comment by rapiz1** [comment]
I have the same issue
